# Buildpack ID and metadata
[buildpack]
id = "com.starkandwayne.buildpacks.discovery"
version = "0.0.1"
name = "Discovery Buildpack"

# Stacks that the buildpack will work with
[[stacks]]
id = "heroku-18"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"
