[lifecycle]
  version = "0.4.0"

[[buildpacks]]
  id = "com.starkandwayne.buildpacks.discovery"
  uri = "."

[[order]]
[[order.group]]
  id = "com.starkandwayne.buildpacks.discovery"
  optional = true

[stack]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
  build-image = "cloudfoundry/cnb-build:cflinuxfs3"
  run-image = "cloudfoundry/cnb-run:cflinuxfs3"